version: 'latest'
services:
  db:
    image: mysql:latest
    container_name: pastebin_db
    environment:
      MYSQL_ROOT_PASSWORD: no_doner_for_u
      MYSQL_DATABASE: pastebin_db
      MYSQL_USER: jonlumi
      MYSQL_PASSWORD: legen_mamaqi
    volumes:
      - "./src/database/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "db_volume:/var/lib/mysql"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastebin
    ports: 
      - '3000:3000'
      
volumes:
  db_volume: