version: 'latest'

services:
  db:
    image: mysql:latest
    container_name: pastebin_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pastebin_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./src/database/schema.sql:/docker-entrypoint-initdb.d/1.sql"  # Mount the schema.sql file into the MySQL container's initialization directory
      - "db_volume:/var/lib/mysql"  # Mount volume for MySQL data persistence

  app:
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile
    container_name: pastebin
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/pastebin_db
    ports: 
      - '3000:3000'  # Map port 3000 from the host to port 3000 in the container
    depends_on:
      - db

volumes:
  db_volume:  # Create a named volume for MySQL data persistence
